id: P009301
initial_creation_type: ocr
source_metadata:
  id: bdr:W21909
  title: རྒྱ་བོད་གཏམ་དཔེ་ངོ་མཚར་ཕྲེང་བ།
  author: ''
  volumes:
    ebc2563e0a6741c0a57c0808aa0a88cc:
      image_group_id: I1KG15017
      title: ''
      volume_number: 1
      total_pages: 490
      base_file: v001.txt
